### ISSUE TITLE
Is "working directory" considered equivalent to "working tree"?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1059]
Currently having an animated discussion on the Git mailing list regarding terminology, and while the consensus is that "working tree" refers to the entirety of the checked out content (regardless of where you happen to be "cd"ed in the middle of that), the phrase "working directory" is a little more problematic and not quite so clear-cut.
Does the Pro Git book treat those two phrases as equivalent?

**Comment by jnavila** [comment]
FWIW, I don't think the term "working tree" was already coined when the book was written, so there's no specific concept attached to it, so if it was used, it had probably the same meaning as "working directory".

My personal feeling is that "working tree" stands for the project's tree that is checked out, no matter where your shell's CWD is, and the "working directory" is your CWD, i.e. a subdir of the working tree.

**Comment by ben** [comment]
I believe the manpages use the term "worktree" to indicate the full tree of directories and files checked out onto disk. That's not in common use for mortal humans, though, so we use the terms "worktree", "working tree", and "working directory" interchangeably. Again, it's a colloquialism, and not exactly correct, but I think we're reflecting common usage of those terms.

Another angle: we don't use the term "current working directory" anywhere in the book. All of our examples are performed from the root directory of the repository, so CWD and WD really are the same thing.

I'm going to close out this issue, since there doesn't seem to be anything actionable here, but feel free to reopen if you think something needs to be changed.

**Comment by PeterHorniak** [comment]
[This page](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics) seems to have a typo.
Figure 6 says "Working Directory" but the surrounding text talks about "Working tree".
Could the page please define both terms, or standardise on one term?

![image](https://user-images.githubusercontent.com/19855973/47252980-dd6fa880-d498-11e8-9c89-7399060620dc.png)
