### ISSUE TITLE
Why move from md to asciidoc(tor) ?

### ISSUE THREAD

**Issue by git001** [progit/progit2#1149]
I plan to create a ebook and see that your first version is based on pandoc/md and the second one on asciidoc(tor).  
It would be nice when you can tell us why this change happen especially as the module is declared as _alpha_ version https://github.com/asciidoctor/asciidoctor-epub3#project-status

Thank you for your a patience.

**Comment by ben** [comment]
Markdown is great for smaller documents, but it's missing a few features that we needed for this book. We needed an index, and even Pandoc can't do this with Markdown. We also wanted extended control over figures, and true multi-file support. You can get those with Pandoc, but with Asciidoc they're built into the spec.

I'm going to close this since there's nothing actionable here, but if you have any more questions I'll be happy to answer.

**Comment by nobozo** [comment]
On 12/11/2018 8:24 AM, Ben Straub wrote:
> Markdown is great for smaller documents, but it's missing a few features 
> that we needed for this book. We needed an index, and even Pandoc can't 
> do this with Markdown. We also wanted extended control over figures, and 
> true multi-file support. You can get those with Pandoc, but with 
> Asciidoc they're built into the spec.
> 
> I'm going to close this since there's nothing actionable here, but if 
> you have any more questions I'll be happy to answer.

I agree with all the above, but one unfortunate side effect of going to
asciidoc is that it's harder to use GitHub Pages now. There are various
schemes to get around this, but they're a burden.

Jon

**Comment by ben** [comment]
GitHub pages was never a delivery target for us. If it is for you, you have lots of options: you could write in Markdown, you could automate generating a static site using Asciidoctor on every push to `master`, you could set up a custom builder on [Netlify](https://www.netlify.com/), or probably five other things I'm not thinking of right now. The world is your oyster. 😄
