### ISSUE TITLE
I can't understand why backslash is necessary.

### ISSUE THREAD

**Issue by ju-hyun-park** [progit/progit2#1172]
<img width="933" alt="2019-02-10 9 46 43" src="https://user-images.githubusercontent.com/45566233/52533878-b3aafc00-2d7d-11e9-937b-33cb161473d2.png">

----

In the above picture, why backslash(`\`) is necessary?  
Is it( `git rm log/*.log` ) wrong? in my opinion, `git rm log/\*.log` literally remove `*.log` file in log directory. For example, A.log, B.log, C.log will not be removed.

If my comment is wrong, could you explain it for more detail?

**Comment by jnavila** [comment]
suppose that before running this command, you ran:

```shell
$ rm log/A.log
```
Then, with the version `git rm log/*.log` you would only commit the removal of `B.log` and `C.log`, because the expansion of the `*` is done by the shell, and `A.log` is no longer in your working copy (but still followed in git), whereas `git rm log/\*.log` prevents the expansion by the shell, and the expansion is done by git which will remove also `A.log`, even if it's no longer in your working tree.

**Comment by ju-hyun-park** [comment]
That picture in [02-git-basics/recording-changes.](https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/recording-changes.asc#removing-files)

**Comment by ju-hyun-park** [comment]
@jnavila thanks a lot. I've understood.
