### ISSUE TITLE
Would breaking "Stashing and Cleaning" into two sections make more sense?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#1184]
Rather then the single section "Stashing and Cleaning," I'm convinced that the content would flow better if there was a "Cleaning" section, *followed* by "Stashing." Cleaning is a somewhat simpler concept, and I think it would lead more naturally into stashing, rather than the order it's in now.

**Comment by ben** [comment]
IIRC we smushed them into the same section because there just wasn't that much content for either one to stand alone. The only good rationale for putting them together is that they both fall under "other stuff you can do with your working directory."

The order doesn't seem (to me) to matter, either – it seems to me that about the same number of readers will want `stash` before `clean` as the other way around. Neither one builds on the other conceptually; it's "how to save stuff without committing" vs "how to delete stuff."

**Comment by rpjday** [comment]
I can see your logic, but I think you're not giving either of those commands the credit they're due in terms of their complexity these days. I'm not going to do anything about this (yet), but I'm still going to ponder on it.
