### ISSUE TITLE
Add some hints on when to use the --no-metadata switch and when not

### ISSUE THREAD

**Issue by CodingSpiderFox** [progit/progit2#1312]
**Which version of the book is affected?**
v2: https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git

**Describe the bug:**
There is this command `git svn clone http://my-project.googlecode.com/svn/ \
      --authors-file=users.txt --no-metadata --prefix "" -s my_project` and the text paragraph before that line says `You can also tell git svn not to include the metadata that Subversion normally imports, by passing --no-metadata to the clone or init command (though if you want to keep the synchronisation-metadata, feel free to omit this parameter).`

Now I feel a bit unsure on what to do. I don't want to loose any data during migration from SVN to Git (and I assume 99% of the time this is true for anyone else) - I want to migrate all data that Git can migrate from SVN.

**Expected behavior:**
I see two possibilities here (both might be applied at the same time):

a) Remove the --no-metadata switch from the suggested command line string
b) Provide a list of possible use-cases where this switch might be helpful or needed.

**Desktop:**
Windows 10

**Comment by CodingSpiderFox** [comment]
So after trying out the command with `--no-metadata` and without this switch, it seems that the only difference is that with `--no-metadata`, the `git-svn-id` lines are missing. So my first assumption might be wrong, as I don't see a practical use for keeping this ID, it might be fine to always use the --no-metadata switch.

The documentation should just be a bit clearer on what this switch does.

**Comment by ben** [comment]
The metadata that's being mentioned is the data needed so that Git knows how to send commits back into Subversion. If you're using Git as a front-end for a svn repo, you'll want to keep it around, but if you're doing a one-way conversion, you won't need it. The latter scenario is what this chapter is about (_"Migrating to Git"_), so we recommend removing it.

If you can think of a way of dropping this technical detail into the text without bogging down the workflow too much, I'd happily review a PR.

**Comment by CodingSpiderFox** [comment]
Thanks for the clarification
