### ISSUE TITLE
Is the `status.json` file in use?

### ISSUE THREAD

**Issue by Morganov** [progit/progit2#1379]
I see that all values in file `status.json` are equal to zero.
Is this file used somehow or it's better to remove it to avoid any confusion?

**Comment by ben** [comment]
Looks like it's used for the [translation repositories](https://github.com/progit/progit2/blob/master/TRANSLATION_NOTES.asc#translation-status), and it might be used for the "partial translations available for" area on the [website](https://git-scm.com/book/en/v2). Probably worth keeping it so that new translation forks have a file in the right place with suggested content.
