### ISSUE TITLE
Figure 79 may be error.

### ISSUE THREAD

**Issue by jiangranye** [progit/progit2#1386]
The line from "C13" to "C2" and line form "C16" to "C2" in figure 79 may be not needed.

address:
https://github.com/progit/progit2/master/master/images/large-merges-2.png
https://github.com/progit/progit2/master/master/images/large-merges-2.svg

Figure 79:
![figure 79](https://github.com/progit/progit2/raw/master/images/large-merges-2.png)

**Comment by ben** [comment]
The idea we're trying to convey is that C13 is a merge commit, with C2 and C4 as parents. C16 is a merge commit with C2 and C12 as parents. This diagram is kind of hard to look at, but it _is_ accurate for this workflow. Does that make sense?

**Comment by jiangranye** [comment]
The C2 is the parent of C4 and C12. Then if merge with C2 and C4 as parents, or C2 and C12 as parents, there will not generate a new commit but just a fast forward at C2 or nothing happen in C4 and C12. I tried something similar just now.

**Comment by jiangranye** [comment]
> The C2 is the parent of C4 and C12. Then if merge with C2 and C4 as parents, or C2 and C12 as parents, there will not generate a new commit but just a fast forward at C2 or nothing happen in C4 and C12. I tried something similar just now.

I use git to test the scenes before. But when I use github to test the scenes, there generate a new commit for pull request. Because the book is used to describe git, deleting the line form C13 to C2 and the line from C16 to C2 may be more suitable.

**Comment by ben** [comment]
In this example, the maintainer is trying pretty hard to create merge commits, using the `--no-ff` flag when merging. The goal here isn't to produce the most linear history, but to create a commit for each branch that's proposed for the next release. That way, if `tv/rebase-stat` is dropped from the plan for the next release, the fix is to just remove one merge commit from the series, rather than a complicated rebase to undo a fast-forward merge. Does that make sense?

**Comment by Morganov** [comment]
> I use git to test the scenes before. But when I use github to test the scenes, there generate a new commit for pull request. Because the book is used to describe git, deleting the line form C13 to C2 and the line from C16 to C2 may be more suitable.

There is a difference between merging branches in Git and merging PR at GitHub:
* Git uses fast-forward by default where it possible to avoid redundant commits and keep your history clean
* GitHub creates a merge commit by default to save in history information about both participants: commiter and author. Additionally, the merge commit could act as the logical "end of work" for feature branch.

Anyway, you can [disable such behavior for git](https://git-scm.com/docs/git-config#Documentation/git-config.txt-mergeff), or select another merge option for PR at GitHub.

![github_merge_options](https://user-images.githubusercontent.com/16842235/75919364-73c62380-5e6e-11ea-8802-f3b2acdb73d7.png)



> Because the book is used to describe git, deleting the line form C13 to C2 and the line from C16 to C2 may be more suitable.

In this particular case, the collaboration process is described.
In real life, the collaboration process could be quite complex. And it's really helpful to have a history as "who - do - what" and to have a possibility to easily revert a dozen changes.


**Therefore, the mentioned situation is NOT an error - it's by design.**

**Comment by jiangranye** [comment]
I tried and now I understand.
Thank you for your contribution and help.
I'll close this issue.
