### ISSUE TITLE
Discussion post: why does the book have section on SCM's that are not git?

### ISSUE THREAD

**Issue by HonkingGoose** [progit/progit2#1456]
Hi @ben, I found another thing that might be good to discuss also, this is related to my findings at: #1452 

What is the purpose of including other SCM's in a book about Git?
Is it to contrast and highlight differences/similarities in concepts, or is it to help migrate from some other SCM to Git?
Because sections like those on Perforce, SVN, Mercuarial and TFS have all seen commits at least 2 years back. So I'm wondering whether those sections are still fit for purpose or not?

I'm talking about the sections that you can find here:
https://github.com/progit/progit2/tree/master/book/09-git-and-other-scms/sections

**Comment by ben** [comment]
Because Git doesn't live in a vacuum, and many users are either migrating to Git or need to use Git as part of a larger ecosystem.

Most (I think) of the content in that directory is about migrating from other systems into Git, which I think is one of the most valuable things this book does. The rest is about using Git as a client to other systems, which is mostly a niche thing, but for those who use it is a beloved feature.

**Comment by HonkingGoose** [comment]
Fair enough, that answers my questions. I'll stop bothering you about the outdated sections in that part then. :smile:

**Comment by ben** [comment]
I've long since made my peace with the fact that our content will sometimes be out of date. It _is_ important that it be correct though, so if you spot something that's inaccurate in a way that makes it useless, I'm all ears.

Going to close this. Feel free to reopen if you think there's something specific and actionable.
