### ISSUE TITLE
Include GitHub CLI in GITHUB section

### ISSUE THREAD

**Issue by NumberPiOso** [progit/progit2#1530]
GitHub CLI is available for repositories hosted on GitHub.com and GitHub Enterprise Server 2.20+, and to install on macOS, Windows, and Linux. [github cli](https://github.com/cli/cli).

I guess this should be added to chapter 6.5 *GitHub - Scripting GitHub*.

**Comment by HonkingGoose** [comment]
Thanks for opening a issue, and contributing to the ProGit2 project! :smile: :+1: 

As luck would have it, I already made a pull request to add a tip about the GitHub CLI, you can review it at #1527.
I linked this issue, so that when the pull request is merged, this issue will be closed automatically.
