### ISSUE TITLE
Mistake in the new "git restore" section?

### ISSUE THREAD

**Issue by Fabien-jrt** [progit/progit2#1533]
The ["undo things"](https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/undoing.asc#unmodifying-a-modified-file-with-git-restore) section  mention that:

"It’s important to understand that `git restore --staged <file>` is a dangerous command. Any local changes you made to that file are gone — Git just replaced that file with the most recently-committed version. Don’t ever use this command unless you absolutely know that you don’t want those unsaved local changes."

I realised that  the warrning added is more about the `git restore <file>` command.
Indeed, this command throw away my local work.

The `git restore --staged <file>` command, however, unstage the file in question.

The only thing I found about it is [this comment](https://github.com/progit/progit2/pull/1511#issuecomment-691441232), originally posted by @HonkingGoose in the [pull request conversation](https://github.com/progit/progit2/pull/1511).

Do I missed something?
Do we need to remove the  `--staged` flag?

**Comment by HonkingGoose** [comment]
Good catch!

I've tried to get my work destroyed by using `git restore --staged` and it doesn't work, because I still have a saved copy in the working directory.

What DOES throw away my work is using `git restore` before any changes have made it to the staging area.

I'm not sure if there are any edge-cases where you would be able to permanently throw your work away with `git restore --staged <file>`? Maybe when some changes are staged, and some other changes are not staged, especially if you edit the same lines. Maybe @ben can chime in on possible edge-cases.

I suspect you're right though and I just made a error, and the warning should really be about `git restore <file>`... :+1:

**Comment by ben** [comment]
Hmm yeah, looks like I misread the documentation as well. If it's only changing the index, then the most you can lose is the carefully-constructed "draft" of your next commit, which you can rebuild from the changes that are still in your working directory.
