### ISSUE TITLE
Installing Git Section: Reference to Non-Existent Git Version

### ISSUE THREAD

**Issue by OliverSieweke** [progit/progit2#1731]
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### This report is about a single actionable bug.

- [X] I'm reporting a single actionable bug

### This report is about the ProGit book, version 2, English language.

- [X] This bug is not about a translation or old version

### Bug covers book website/pdf

- [X] I confirm the bug is about the book as found on the website/pdf

### Problem is present in the Pro Git book on the website?

- [X] This bug also affects the Pro Git book as published on the website.

### Which version of the book is affected?

Source files

### Describe the bug:

The note on the *Installing Git* section (**Chapter 1 - Getting Started**)  specifies that the book was written with Git version `2.8.0`.
This must be a typo as currently the latest available version is `2.35.1`.

The commit the introduced that mistaken change is #1122.

### Steps to reproduce:

NA

### Expected behavior:

NA

**Comment by ben** [comment]
Not a typo. That line was first written in 2014, when Git 2.0.0 was brand new. According to [the history](https://en.wikipedia.org/wiki/Git#Releases), 2.8.0 was released in 2016, and that patch to change the recommended-minimum version was merged in 2018, so it was probably true then.

Do we need some kind of action here? I don't want to just say "this book works with Git $CURRENT_VERSION," because that's sure to be untrue at some point. It's also kind of silly to recommend a minimum version, when most people will be running something at least a little recent. Should we just remove the mention of the version?

**Comment by OliverSieweke** [comment]
Oh, my bad! My brain somehow repeatedly read the current version as `2.3.51`.
Thanks for the reply, I think it's all good.

While we're talking about it though, maybe the mention of a specific minimum version is not quite necessary. If you'd like to rephrase things slightly, just encouraging people to get a recent version and pointing out that older versions might behave slightly differently, you may want to consider the wording below:

> This book was written using Git version 2. Since Git is quite excellent at preserving backwards compatibility, any recent version should work just fine. Though most of the commands we use should also work even in ancient versions of Git, some of them might not or might act slightly differently.

I'm creating a pull request in case you'd like to include the slight rephrasing, else I'll let you close the issue.

Thank you for the book, most excellent read!
