### ISSUE TITLE
My 2 cents

### ISSUE THREAD

**Issue by elect86** [progit/progit2#205]
Hi,

just two things:
- [here](http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) the image just before ["Creating a New Branch](http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#Creating-a-New-Branch) is confusing and has nothing to do there
- at [Switching Branches](http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#Switching-Branches) the fourth image has an error, 87ab2 belongs to the testing branch

For the rest, very very very nice tutorial, it should deserve much more attention
Cheers

**Comment by dennisschagt** [comment]
Your second point is a duplicate of #136 which is fixed in 87254184fd3642148c284df68c59ae20751ca44a but it is not yet updated on the live [git-scm.com page](http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#divergent_history).

**Comment by HonkingGoose** [comment]
I'm not sure point one is actually true in the current version:
https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#Creating-a-New-Branch

The picture I think @elect86 is referring to:
https://git-scm.com/book/en/v2/images/branch-and-history.png
The text under the figure is: ```Figure 11. A branch and its commit history```

There's a picture of head pointing to ```master```, a second branch labeled ```v1.0```. Both branches point to commit ```f30ab```. My take-away from this picture is: ```master``` and ```v1.0``` are the same currently, and ```master``` is "checked out" because ```HEAD``` is pointing at it.

I'm not sure where there is any confusion in this picture? But maybe I'm missing something...

**Comment by elect86** [comment]
Hey, 

sorry but too much time has passed and I don't remember what I meant :)

**Comment by HonkingGoose** [comment]
Hi @elect86,

I know a lot of time has passed. I'm trying to get this issue tracker cleaned up. There are a lot of older issues open here. And the older the issue gets, the harder it is to determine if the current book has those issues anymore. :smile: 

Thanks for chiming in though! :smile:

**Comment by elect86** [comment]
Yeah, I get it.

I should done also some cleaning on mines..

Anyway, I'll close it

Ciao :)
