### ISSUE TITLE
rebase v.s. merge

### ISSUE THREAD

**Issue by wolfv6** [progit/progit2#246]
In Section 5.2, the author uses the rebase method.
In Section 6.2, the author uses advises to use the merge method rather than the rebase method.
The examples are similar.  Why the inconsitency?

5.2 Distributed Git - Contributing to a Project, subsection Forked Public Project:
>Let’s say the project maintainer has pulled in a bunch of other patches and tried your first branch, but it no longer cleanly merges. In this case, you can try to rebase that branch on top of origin/master, resolve the conflicts for the maintainer, and then resubmit your changes

6.2 GitHub - Contributing to a Project, subsection Keeping up with Upstream:
>You have two main options in order to do this. You can either rebase your branch on top of whatever the target branch is (normally the master branch of the repository you forked), or you can merge the target branch into your branch.

>Most developers on GitHub will choose to do the latter, for the same reasons we just went over in the previous section. What matters is the history and the final merge, so rebasing isn’t getting you much other than a slightly cleaner history and in return is far more difficult and error prone.

**Comment by ben** [comment]
We didn't take a firm stance in the "rebase vs. merge" debate because there isn't a right answer. Git provides both of these capabilities in a first-class way, so it was a top-level goal with the book to demonstrate both of them more or less equally. That way, the reader can make her own decision as to which one fits in a given situation.

This is one of the unfortunate side-effects of Git having two ways of doing a common activity. The more you read, the more you'll see this inconsistency, and there's no real way to "fix" it.
