### ISSUE TITLE
Polish translation (pl)

### ISSUE THREAD

**Issue by davpal** [progit/progit2#269]
I've started with polish translation of progit. Here is my fork of progit2 repo:

https://github.com/davpal/progit2-pl

**Comment by davpal** [comment]
I've translated 1st, 2nd and part of 3rd chapter. Could someone move my repository?

**Comment by jnavila** [comment]
You can ask @schacon

**Comment by jnavila** [comment]
If it's still make sense, you can create an organization `progit2-pl` and migrate the repo to it. Then, we can update the scripts at git-scm.com to activate the publishing (website only).

**Comment by davpal** [comment]
I've transfered repository to organization https://github.com/progit2-pl/progit2-pl

**Comment by jploskonka** [comment]
Hey,
@davpal I'd like to help with further translations, I created PR updating your fork to current state of this repository. It's quite a lot of commits so if anyone has any advice on how to make sure everything still works OK please let me know. If we can make polish fork up-to-date again I'm more than happy to continue work on translating more chapters :)

PR: https://github.com/progit2-pl/progit2-pl/pull/3

I'm linking PR also here because issues on your fork are disabled and I wasn't sure what's the best way to keep everyone interested up to date with discussion, if you no longer have enough time or energy to maintain polish fork please let me know, maybe I can help :)

**Comment by krisfremen** [comment]
@jploskonka Usually you wouldn't merge the english contents into a translated repo.

Preferably do it on a separate branch and after it's been translated, merge it into the master.

**Comment by davpal** [comment]
I agree with @krisfremen. We should focus on moving translation from 1st edition to 2nd first and then translate the rest (never translated) chapters.

**Comment by jploskonka** [comment]
Ah, ok :) I was a bit worried that forked repo is so behind root one, but in this case I will just abort merge and proceed with translating things, even better :D Thank you for input!

**Comment by jploskonka** [comment]
@davpal Hey, I'm wondering about the best way to reuse translations from previous edition, how did you approach it in chapters 1 and 2? Should I just copy texts from old edition where possible and add missing parts and finally just add some tweaks where necessary or is there some better way you figured out? What about authors of first edition translations, should we mention their Github profiles somewhere (as now history will say that those are mine changes if I just commit them)?

I'm almost almost ready with chapter 03, let's see how it goes with finishing it :)

**Comment by HonkingGoose** [comment]
@jnavila It seems this issue has run its course, and can be closed? There's a Pro Git 2 Polish translation repo here: https://github.com/progit2-pl/progit2-pl

---

For all people on the thread, the current guidelines for contributing a translation can be found here:
https://github.com/progit/progit2/blob/master/TRANSLATING.md

**Comment by jnavila** [comment]
Sure :+1:
