### ISSUE TITLE
Upstream shorthand p67 @{upstream} and @{u}

### ISSUE THREAD

**Issue by bobbingwide** [progit/progit2#343]
ProGit 2nd ed. hard copy, p. 67 just below upstream shorthand. Is this a typo? I don't understand the curly bracket stuff.

**Comment by YueLinHo** [comment]
P67 of PDF?

**Comment by bobbingwide** [comment]
p67 of hard copy book.

**Comment by ben** [comment]
Yeah, we didn't dig too deeply into this `rev-parse` syntax. You can check out [the docs](https://git-scm.com/docs/git-rev-parse#_specifying_revisions) if you want to know more.

**Comment by bobbingwide** [comment]
Yeah? It is a typo? or NO, It's not a typo, but "Yeah" it's not explained... and the docs don't make it any easier to understand.

**Comment by ben** [comment]
It's not a typo: `@{u}` and `@{upstream}` are synonyms, and they mean "follow this branch's commit's parents until you get to the place where the corresponding remote branch is pointing, and return that." 

The docs are admittedly pretty unapproachable about this. I'd love to include a section in the book about it, but where should it go? It's pretty esoteric.

**Comment by YueLinHo** [comment]
@ben I don't have a hard copy. Could you please tell me where is it? I still can't find it in all asc files.
Also, how to get more information fomr the page No. of hard copy? Is it equal to the page No. of PDF file or something else?

**Comment by ben** [comment]
Unfortunately page numbers don't map directly between the editions, especially since the electronic editions have had a lot of updates (many of them from you!). I seem to recall discussing with Scott about including a section on the rev-parse syntax, but it's a pretty narrow feature, so in the end it got left out. If it were to be added, I'd think Chapter 7 would be the right place.
