### ISSUE TITLE
Internal link between Chapter 1 and Chapter 3 in history.asc is broken

### ISSUE THREAD

**Issue by crd** [progit/progit2#369]
history.asc contains the link <<_git_branching>> and 1-git-branching.asc has the correct corresponding anchor: [[_git_branching]]

**Comment by ben** [comment]
This is tricky. If you try to follow the link in the GitHub UI, it'll be broken because the destination isn't in the same file. You have to build some kind of output where the destination is visible to the compiler. The link in the [PDF version](https://progit.org/) works just fine. Unfortunately the [online HTML version](http://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git) is broken, though the downloadable HTML from Atlas works. :stuck_out_tongue:

**Comment by crd** [comment]
I had no expectation that inter-github linking would work (although that'd be super cool) -- I was referring to the online HTML version. Is this an asciidoc issue?

**Comment by ben** [comment]
I don't think so. It looks like an issue with how git-scm.com is deployed.

**Comment by crd** [comment]
Good point -- closing this issue and opening one against the git/git-scm.com repository. Thanks!
