### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by bartgenuit** [progit/progit2#372]
As I [understand](http://www.git-scm.com/book/en/v2), this book is licensed under the Creative Commons Attribution Non Commercial Share Alike 3.0 license ([CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/)). However, in my print version of the book (ISBN-13: 978-1-4842-0077-3), no mention is made of this license whatsoever, as far as I could find. I found this interesting, as I like the fact that the book itself is open sourced very much and in this way, you can directly put your newly obtained git knowledge to practice in contributing to the book. 
Also, the [contribution guide](https://github.com/progit/progit2/blob/master/CONTRIBUTING.md) mentions

> Also, you agree to grant such license of your work as is required for the purposes of future print editions to @ben and @schacon. Should your changes appear in a printed edition, you'll be included in the contributors list.

This raises some questions:

1. Why is there no mention of the open source license in the print version?
2. Isn't the mentioning of the license and the contributors mandatory, at least for any content supplied by others than @ben and @schacon?
3. Why is there another license required for print editions? Is the creative commons license in some way incompatible with printing?

**Comment by ben** [comment]
@schacon can correct me, but here are my as-I-understand-it and IANAL answers.

Apress has been granted license (by @schacon and myself as the authors of the original content) to publish their version of the book. If they wish to use the updated source that the community has been improving, they'll have to abide by the CC license. (To answer your last question, I believe the "NC" part of the license would prevent Apress from printing the book and selling it for profit.)

That clause in the contributor's guide is to avoid a specific problem we had for the second edition. Since contributions to the first edition weren't made with this clause, we couldn't use the latest, best version as a starting point for the second edition. We had to throw away a lot of the contributions and improvements, and work from a place where all of the content was of a provenance compatible with our goals: to provide a print version through Apress, digital versions for free, and allow the community to improve and fix the content. If there's ever a third edition, we'll be able to include all the contributions to the second edition.

Does that make sense?

**Comment by bartgenuit** [comment]
Thanks for your answer, I'm beginning to get the full picture I think.

Could you elaborate a bit on the specific problem you described about contributions not being compatible with the goals? Were there any agreements with contributors to the first edition? How were these contributions not usable?

**Comment by ben** [comment]
Well, we had dozens of contributors, and we couldn't be certain of getting all of their agreement to relicense their contributions. Given that, and the tangled history of that repository, it made more sense to throw away all the Internet's improvements and start from the original version that Scott had all the rights to, instead of spending months getting licenses signed. This time around we wanted to avoid that, so contributions have to be licensed in such a way that we can use them (and credit the authors) if and when a 3rd print edition is published.

**Comment by bartgenuit** [comment]
Okay, thanks for the explanation

**Comment by valerio-bozzolan** [comment]
I did not understand whether the repository owner currently wants a commercial monopoly on this project or not.

This should be the only question in deciding whether to adopt a proprietary license.

By the way I recall that the license CC BY-NC is incompatible with Wikipedia, Wikibooks, Wikidata, Wikiversity and the whole StackExchange network including StackOverflow. That is not a smart direction.

**Comment by bartgenuit** [comment]
Hi @valerio-bozzolan, that's a fair point. The NonCommercial clause makes the current license not fully free, and limits the use of this work.

The goal of restricting use of this book to non-commercial cases is probably that you would not want somebody else to profit from your hard work. However, in case of a commercial-allowed license, any profit will be very limited, since the original would also still be available to anybody, under the same conditions. So a publisher, for example, could only ask for a reasonable fee to ship you a paper copy, because you can easily find the original and print it yourself. As can any other publisher.

Actually, I found that Apress [encourages](https://www.apress.com/gp/services/source-code) to license the source code of their books under an open source license such as MIT.
