### ISSUE TITLE
Broken links in Basic page

### ISSUE THREAD

**Issue by Yousha** [progit/progit2#419]
Some links in "1.3 Getting Started - Git Basics" (basics.asc) are broken.

Such as "undoing things", "git brainching", "git basics" and...

**Comment by i-give-up** [comment]
Yeah. Seems like a lot (if not all) the internal cross-reference over all sections are broken on the website. For example in ["1.3 Getting Started - Git Basics"](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics), [the link to Git Branching](https://git-scm.com/book/en/v2/1-git-branching/_git_branching) (among others) is broken. If you look at [the .asc markup](https://raw.githubusercontent.com/progit/progit2/master/book/01-introduction/sections/basics.asc), you find the link to "Git Branching" like this

    We'll explore some of the benefits you gain by thinking of your data this way when we cover Git branching in <<_git_branching>>

From what I googled, it seems like this `<< >>` syntax is for internal cross-referencing which means the link actually goes to `#_git_branching` on the same page. Kind of odd, considering that the Git Branching is on an another page ([Link - rendered](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell), [Link - asc](https://github.com/progit/progit2/blob/master/book/03-git-branching/1-git-branching.asc)).

From [AsciiDoctor's User Manual](http://asciidoctor.org/docs/user-manual/#inter-document-cross-references), it seems like they do support inter-document xref-ing with pretty much the same syntax

    <<path/to/file#,Section Name>>

---

Ah ok, I used AsciiDoctor to compile the source into HTML myself, and I found out that it outputs a single HTML instead of the multi-page document seen on the website, and all the links work fine in the single HTML (as I should). This suggests that some kind of redirection should be done on the website itself instead of fixing the .asc sources.

**Comment by ben** [comment]
This has been noted in several issues over on the website project. I just pinged @schacon in https://github.com/git/git-scm.com/issues/588, we'll track it over there.
