### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by u-gajin** [progit/progit2#453]
2.1 Git Basics - Getting a Git Repository

http://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository

Getting a Git Repository

If you’re starting to track an existing project in Git, you need to go to the project’s directory and type:

$ git init

How do you go to to the project's directory?

**Comment by ben** [comment]
Git's a tool that requires that you use a terminal. If you've never done that, check out these introductions:

- [Mac OS X](http://mac.appstorm.net/how-to/utilities-how-to/how-to-use-terminal-the-basics/)
- [Linux](http://www.instructables.com/id/Linux-Terminal-Basics/)
- [Windows](http://www.cs.princeton.edu/courses/archive/spr05/cos126/cmd-prompt.html)

**Comment by u-gajin** [comment]
Thanks Ben, but that isn't the problem. There are a few issues here, which appear to be missed. 

First the comment; 'You can get a Git project using two main approaches.'  This we are told is by initialising, or cloning a repository. What I think is intended here is there are two main approaches, which are; a)  Initialising and/or b) Cloning. However, neither term is explained. 

Moving on, the issue that I was trying to raise is this. 'If you’re starting to track an existing project in Git, you need to go to the project’s directory and type:' '$ git init', simply does not make sense. It is a poorly constructed sentence. It may make sense if you now what is intended, but the intention isn't clear.

Is tracking an existing project the same as Initialising a project? It doesn't sound the same to me, and  tracking a project appears not to be the same thing as cloning. Let's assume we want to start tracking an existing project. What then, in this context, does 'go to' mean? Why not provide an exemplar project to 'go to' and instructions on what do in order to 'get there'? BTW, the 'Git Internals' link is broken. If 'and type: $ git init'' means type '$ git init' (without the $) into a Terminal window, then again why not say so?

We are told, 'This creates a new subdirectory named .git that contains all of your necessary repository files – a Git repository skeleton.' Where is this created, and what repository files are created (if any)?

It would be useful, too, if there were instructions on how to undo, the above.

The paragraph continues: 'If you want to start version-controlling existing files (as opposed to an empty directory), you should probably begin tracking those files and do an initial commit. You can accomplish that with a few git add commands that specify the files you want to track, followed by a git commit:

$ git add *.c
$ git add LICENSE
$ git commit -m 'initial project version'
We’ll go over what these commands do in just a minute. At this point, you have a Git repository with tracked files and an initial commit.'

What files are these that we are version-controlling, and I cannot find an explanation for the above commands.

Thanks again for considering matters,

-u

**Comment by ben** [comment]
(Regarding broken links: this is [known](https://github.com/git/git-scm.com/issues/588).)

Okay, I see what you're getting at. We had to make some basic assumptions about the level of technical expertise of the reader, otherwise we'd spend a lot of time explaining how to turn a computer on, how to log in, how to start a terminal, etc. Our audience is software developers, so we can count on their abilities to open a terminal, use `cd`, and recognize filename patterns like `*.c`. That section isn't meant to be a soup-to-nuts walkthrough of everything that's happening, or even a live example, it's just a sample of the kinds of commands you'll be seeing further on. If the reader wants to know what's going on behind the scenes (on a deeper level than "this creates the `.git` folder, and turns this directory into a Git repo"), they can check out the internals chapter.

Would you like to submit a PR that makes it better? I can see your point, but I'm not sure exactly how this section should read to alleviate your concerns.

**Comment by nijagu-ugajin** [comment]
It appears to be a soup starter:
  Chapter 1: Getting Started
  Chapter 2: Git Basics
What more is there to say?
