### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by salahzidi** [progit/progit2#468]
I opened this issue to start an arabic translation for this great book:
https://github.com/salahzidi/progit2

**Comment by ben** [comment]
Ping @schacon

**Comment by schacon** [comment]
Hey @salahzidi, it doesn't look like much is actually translated. Once you get a chapter or two done, let me know and I can turn it into an official project.  Thanks!

**Comment by salahzidi** [comment]
OK @schacon, I'm working on it!

**Comment by jaksz** [comment]
Hey, is this still of interest? I can contribute to the Arabic translation.

**Comment by HonkingGoose** [comment]
@jnavila It seems this issue has run its course, and can be closed? 

This might be the "official" repository for the translation into Arabic? 
https://github.com/progit2-ar/progit2 
If so, it needs to be listed in our TRANSLATE.md file, so that we point others the right way.

Anyway, it doesn't seem that any version of the Arabic Translation is yet pulled into the git-scm source. Arabic has the ```ar``` ISO code, I see no link ending on ```ar``` in the translations list at git-scm. I've checked the linked repository above, and there is not much translated yet.

---

For all people on the thread, the current guidelines for contributing a translation can be found here:
https://github.com/progit/progit2/blob/master/TRANSLATING.md

**Comment by jnavila** [comment]
Ditto

**Comment by HonkingGoose** [comment]
@jnavila Do you want a pull-request for this one, so that it's mentioned in the TRANSLATING.md table? Or do you want to leave this one as-is?

**Comment by jnavila** [comment]
Good!
