### ISSUE TITLE
Import from Subversion: Missing step?

### ISSUE THREAD

**Issue by mkarg** [progit/progit2#487]
When I am following the steps described in the book to import a complete SVN repository into a GIT repository, I end up with more branches than SVN originally contained:
```
$ svn ls branches
  jaxrs-1.1
  performance
  
$ git branch
* master
  origin/jaxrs-1.1
  origin/jaxrs-1.1@120
  origin/jaxrs-1.1@129
  origin/jaxrs-1.1@13
  origin/performance
  origin/trunk
```
* The prefix `origin` has to be removed.
* `origin/trunk` certainly points to the same hash code, so it should *simply be* `master`: The solution is to simply remove that branch.
* The book should explain that peg-versions (`@`) will exists after the migration as there is no other way to express this semantics in GIT.

**Comment by ben** [comment]
Right, git-svn is trying to treat the Subversion repository as a remote, which is why you get the `origin/` prefix. The idea here is that you can use Git for local operations, and when you `git push` to a git-svn remote, it'll result in a Subversion revision.

Further down on that page, it's recommended that you run commands like this:

```shell
$ cp -Rf .git/refs/remotes/* .git/refs/heads/
$ rm -Rf .git/refs/remotes
```

That converts all the `origin/*` remote branches to regular branches, so part of your problem is solved. I'd _love_ it if you submitted a PR to correct the issue with peg versions, though.

**Comment by mkarg** [comment]
You're right, but you misunderstood my point: I am talking about the chapter on *migration* from svn to git. In *that* context, the following is simply wrong, as nobody wants to push back into svn anymore.
* Your commands create branches beginning with the prefix "origin". That prefix must get stripped when migrating to GIT. Nobody wants a branch which was called "foo" in SVN to be called "origin/foo" in GIT. Just as you do it correctly with tags a few lines above!
* There is nothing *wrong* with peg-revisions. In fact what I proposed is that the book tells the user that a preg revision is *not* a bug.

If it is still not clear I simply will submit a PR that does all the needed fixes.

**Comment by ben** [comment]
:heart_eyes: Closing this, it looks like your PRs will address it one way or another.
