### ISSUE TITLE
Broken link in Chapter 3.1 (english language)

### ISSUE THREAD

**Issue by zergood** [progit/progit2#497]
Second abstract in Branches in a Nutshell.
Sentence begins with:  As you may remember from *Getting Started*...

*Get Started* link is broken.

**Comment by ben** [comment]
This is a common issue when you're reading the rendered AsciiDoc on GitHub. It's structured so that the Atlas renderer can produce correct links, not for GitHub viewing. The rendered PDFs have correct links, and although there seems to be an issue with git-scm.com links (see https://github.com/git/git-scm.com/issues/588), those are at least identifying the correct section to link to.
