### ISSUE TITLE
Broken link to basic merging

### ISSUE THREAD

**Issue by oliviadodge** [progit/progit2#513]
The link to basic merging in the file progit2/book/07-git-tools/sections/advanced-merging.asc does not lead anywhere.

**Comment by ben** [comment]
If you read the files here the links don't work. This is because links are relative to a conceptual "root directory" that doesn't exist any other time than when Atlas is doing the build. They work in the PDFs, ebooks, and the raw HTML that Atlas spits out, but the git-scm.com website's import has been broken for a while. We're still waiting on @schacon to help fix it.

In the meantime, I'm closing this, since there isn't anything we can do about it here. There are several reports over on [the git-scm.com repo](https://github.com/git/git-scm.com/issues/633). Thanks!

**Comment by oliviadodge** [comment]
Sorry to repeat the issue! Thanks for responding, though. I was on the git-scm.com website when I found the broken link and thought I'd mention it. Glad it has been caught.
