### ISSUE TITLE
English (Chapter3.2) Wrong labeling in graphic for last commit

### ISSUE THREAD

**Issue by OutsourcedGuru** [progit/progit2#524]
I'm guessing here that you wanted to indicate C6 for the merge commit which is pointed to by master.

**Comment by YueLinHo** [comment]
Do you mean **Figure 3-17**?

![image](https://cloud.githubusercontent.com/assets/5831804/13765337/653a78be-ea93-11e5-86d8-3b3fd1363d6b.png)

**Comment by YueLinHo** [comment]
Do you mean **Figure 3-17**?

![image](https://cloud.githubusercontent.com/assets/5831804/13765337/653a78be-ea93-11e5-86d8-3b3fd1363d6b.png)

If so, I checked this history of file `book\03-git-branching\images\basic-merging-2.png`, looks like it has been fixed in commit 3491527b33251fcacd8d2964bf7fb5e0f1cfe455 by @ben on 2014-11-25. Oh! long time ago!

So, maybe something worng...

**Comment by YueLinHo** [comment]
Duplcate #286

**Comment by YueLinHo** [comment]
Please close this issue as duplcate #286. :smile:

**Comment by jnavila** [comment]
Again, an issue with git-scm.com I guess... :sob:
