### ISSUE TITLE
Does log "--all-match" option have anything to do with --author matching?

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#666]
p. 64 claims: "(Note that if you want to specify both author and grep options, you have to add --all-match or the command will match commits with either.)"

That's not what "man git-log" says; rather, it says, 
   --all-match
           Limit the commits output to ones that match all given --grep, instead of ones
           that match at least one.

I see no reference to the --author option there.

rday

**Comment by ben** [comment]
Here's the entire paragraph, for context:

> You can also filter the list to commits that match some search criteria. The `--author` option allows you to filter on a specific author, and the `--grep` option lets you search for keywords in the commit messages. (Note that if you want to specify both author and grep options, you have to add `--all-match` or the command will match commits with either.)

Turns out you're right. The default behavior is to combine multiple `--grep` options with a logical `OR`, but other flags (or at least `--author`) with a logical `AND`. 

Want to submit a PR? I'd love it if you got onto the contributor list for fixing this.

**Comment by rpjday** [comment]
I'll whip up a patch for this in the near future.

**Comment by rpjday** [comment]
Since I've made an explanation for this part of one of my earlier patches, we can close this.
