### ISSUE TITLE
Shouldn't "remote references" be references **to** your "remote repositories"?

### ISSUE THREAD

**Issue by JohnLukeBentley** [progit/progit2#715]
https://github.com/progit/progit2/blob/master/book/03-git-branching/sections/remote-branches.asc

Currently:
> Remote references are references (pointers) in your remote repositories, including branches, tags, and so on.

Suggested correction:
> Remote references are references (pointers) ~~in~~ *to* your remote repositories, including branches, tags, and so on. [Without the emphasis in production].

Does my suggested correction betray a misunderstanding on my part?

By the way, a superb book. Generally very clearly written and structured.

**Comment by ben** [comment]
Thanks! We're pretty proud of the book, and we're glad you're finding it useful. 😊 

As for your suggestion, I see what you're getting at, but I'm still leaning towards the original wording. 

A "reference in the remote repository" suggests that this reference belongs to that other repo, and your repo is just borrowing it. A "reference to the remote repo" has more of a sense that this pointer belongs to you, but that it points to something that belongs to that other repo. Neither of these is factually wrong, but I think the first sense is a more-constructive way of thinking about Git's repository structure. Remote refs aren't really _yours_, exactly. Does that make sense?

**Comment by JohnLukeBentley** [comment]
Thanks Ben, that's helpful.

At the point of creating this thread: I was (and am) new to Git; was up to Chapter 7 in your book; and had preformed a few experiments using the command line, SmartGit, Github desktop, and the Github website. A somewhat pristine representative of your target audience in other words, we might say. 

Your post prompted me to jump ahead to read the the first part of Chapter 10, Git internals, up to and including the "Refspec" section. Reading your post and that part of chapter 10 might, therefore, have a cleared up my confusion (we'll see). 

(On the debate mentioned in Chapter 10, about where the chapter should be located: I think you've probably got it where it should be).

I'm mindful not to turn this thread into a mere personal tutorial from one of the book's authors. Rather, I'm might draw on your expertise to verify my understanding so we might, then, identify if any of my confusions point to ways in the which the book could be improved. 

So I'd ask for your favour, firstly, in confirming whether the following understanding is accurate ...

# My current understanding

## A "remote": a local mapping to a remote repo.

"A remote" is a mapping of a friendly name, only seen locally, to the url of the remote repo. For example (I'm in Powershell on Windows):

    PS C:\Users\John\Documents\Sda\Code\Git\Examples\Spoon-Knife> git remote --verbose show
    origin  https://github.com/JohnLukeBentley/Spoon-Knife.git (fetch)
    origin  https://github.com/JohnLukeBentley/Spoon-Knife.git (push)
    upstream        https://github.com/octocat/Spoon-Knife.git (fetch)
    upstream        https://github.com/octocat/Spoon-Knife.git (push)

The internals are more complex. Stored in a section in .git/config is the remote friendly name (as understood by this local repo) to a URL and a fetch "refspec" which maps remote branches to locally understood "remote tracking-branches". 

> The format of the refspec is an optional `+`, followed by `<src>:<dst>`, where `<src>` is the pattern for references on the remote side and `<dst>` is where those references will be written locally. (Chacon and Straub 2014, ch. 10, sec. The Refspec).

E.g.:

    [remote "origin"]
      url = https://github.com/JohnLukeBentley/Spoon-Knife.git
      fetch = +refs/heads/*:refs/remotes/origin/*
    [remote "upstream"]
      url = https://github.com/octocat/Spoon-Knife.git
      fetch = +refs/heads/*:refs/remotes/upstream/* 

## References 

### General

Every repo will have references. There'll be references in the local repo and references in remote repos. 

References are pointers.

References (or "refs") are:
> [files] in which you can store the SHA-1 value under a simple name (Chacon and Straub 2014, ch. 10, sec. Git references).

An example reference:

    PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> Get-Content .git\refs\heads\master
    7ffa8cf641cbaccdc435724f61f3a18cefb0f25c

But there are also "symbolic references":

> By symbolic reference, we mean that unlike a normal reference, it doesn't generally contain a SHA-1 value but rather a pointer to another reference. If you look at the file, you'll normally see something like this: ... (Chacon and Straub 2014, ch. 10, sec. The HEAD)

An example symbolic reference:

    PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> Get-Content .git/HEAD
    ref: refs/heads/master

So, it seems, a git "reference" is either: 
1. "a file in which you can store the SHA-1 value under a simple name"; or 
2. "a pointer to another reference" that stores a SHA-1 value under a simple name.

### Local SHA-1 References

Local SHA-1 references include (at least):

* Branches. heads (e.g. .git/refs/heads/master). That is, "a ... pointer .... to the head of a line of work" (Chacon and Straub 2014, ch. 10, sec. Git references).
* Remote tracking-branches (e.g. .git/refs/remotes/origin/master). "the [SHA-1] value you last pushed to that remote for each branch in the refs/remote directory".

  > Remote-tracking branches are references to the state of remote branches. They're local references that you can't move; they're moved automatically for you whenever you do any network communication. Remote-tracking branches act as bookmarks to remind you where the branches in your remote repositories were the last time you connected to them. (Chacon and Straub 2014, ch. 3, sec. Remote Branches)

* Tags (e.g. .git/refs/tags/0.10). "a tag generally points to a commit ... it's like a branch reference, but in never moves - it always points to the same commit but gives it a friendlier name".

Show local references:

    PS C:\Users\John\Documents\Sda\Code\Git\Examples\Spoon-Knife> git show-ref
    db6eab079a424cb9bbc70464e69a838ec8a72b69 refs/heads/issue315-fruit-handling-20170205-1022
    736cfe9d2fd8c199fd1d305323a775a9052ddb6f refs/heads/master
    d0dd1f61b33d64e29d8bc1372a94ef6a2fee76a9 refs/remotes/origin/HEAD
    f439fc5710cd87a4025247e8f75901cdadf5333d refs/remotes/origin/change-the-title
    d0dd1f61b33d64e29d8bc1372a94ef6a2fee76a9 refs/remotes/origin/master
    58060701b538587e8b4ab127253e6ed6fbdc53d1 refs/remotes/origin/test-branch
    f439fc5710cd87a4025247e8f75901cdadf5333d refs/remotes/upstream/change-the-title
    d0dd1f61b33d64e29d8bc1372a94ef6a2fee76a9 refs/remotes/upstream/master
    58060701b538587e8b4ab127253e6ed6fbdc53d1 refs/remotes/upstream/test-branch

... and examine your .git\refs directory.

### Local symbolic reference, to current local branch.

The HEAD file (.git/HEAD) "a symbolic reference to the branch you are currently on"  (Chacon and Straub 2014, ch. 10, sec. The HEAD).

    PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> Get-Content .git/HEAD
    ref: refs/heads/master

### Remote references

> Remote references are references (pointers) in your remote repositories, including branches, tags, and so on. You can get a full list of remote references explicitly with `git ls-remote [remote]`. (Chacon and Straub 2014, ch. 3, sec. Remote Branches) 

Show remote references:

    PS C:\Users\John\Documents\Sda\Code\Git\Examples\Spoon-Knife> git ls-remote origin | Out-Host -Paging
    d0dd1f61b33d64e29d8bc1372a94ef6a2fee76a9        HEAD
    f439fc5710cd87a4025247e8f75901cdadf5333d        refs/heads/change-the-title
    d0dd1f61b33d64e29d8bc1372a94ef6a2fee76a9        refs/heads/master
    58060701b538587e8b4ab127253e6ed6fbdc53d1        refs/heads/test-branch
    d5697ad282ca597e5e935e177199431e2148c585        refs/pull/1000/head
    87f5cf9becb9490d77bb70e19823a84372b5d012        refs/pull/1000/merge
    3d039152a687b3c00ed6454caa77b2483a8e83d8        refs/pull/10000/head
    6d2362522c2badf5dacbd4b4c43f595d4aaf386d        refs/pull/10000/merge
    aabacac148f78c4fa724ab10287ea40228ef9ae6        refs/pull/10001/head
    490a6f0ed1a0c1751bff74b733787e8f480bd644        refs/pull/10001/merge
    bc01022520a0f8e9098304b9472a7edecc46a2a1        refs/pull/10002/head
    ...

That command looks up the remote repo over the internet. If you disconnect your local machine from the internet and try again you get

    PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> git ls-remote
    fatal: unable to access 'https://github.com/JohnLukeBentley/example/': Couldn't resolve host 'github.com'

### Remote tracking branches.

"Remote tracking branches" are a kind of local SHA1 reference. They point to the last commit of branches in remotes, as of the last time the local repo communicated with the remote repo.

# Key points about my current understanding of remotes, references, and remote tracking branches.

If the above is accurate are the following key points about my current understanding correct...

In terms of the git data structure of a repo:

* A "remote", although a pointer (the friendly name points to the remote url), is not a "reference" nor a "remote reference".
* "Remote references" aren't stored in your local repo. Unlike, that is, "references" returned by `git show-ref` which are in effect "local references".
* A "remote tracking-branch" is not a kind of "remote reference". Rather a "remote tracking-branch" is a "local reference" to the state of a remote branch (at the point of last network communication with the remote repository).

?

**Comment by YueLinHo** [comment]
![image](https://cloud.githubusercontent.com/assets/5831804/22729278/080bf4d6-ee1d-11e6-84cd-d020a053b482.png)

**Comment by ben** [comment]
It looks like your current understanding (which was fantastically formatted and referenced, btw) is pretty correct. It just seems like the shorthand for some of the concepts has you confused.

When you're talking to the Git command-line:

-  a **"remote"** is that part of the config file you found; a URL and a refspec. Conceptually, this means a connection to repo that lives somewhere else, that Git can transfer objects to and from
- a **"remote tracking branch"** is a read-only ref that represents the state of the remote repository, at the point in time at which it was last fetched. `origin/master` is an example; it points to the last-known position of the `master` ref in the repo known as "origin". 
- a **"remote reference"** is the position of a reference in another repository. For example, during an `ls-remote` operation, the other repo will report the object pointed to by its `master` branch, and in the context of this operation (or something like a fetch), that's what would be called the "remote reference."

But colloquially, when we're speaking English to each other, these things are sometimes conflated. "Remote" can mean either the other repo **or** the URL+refspec in the configuration. "Remote refs" and "remote-tracking branches" are the same if you're looking at the output of `git branch -a`, but not if you're talking about a failed `git fetch`.

Part of the challenge of writing a technical book is getting the balance right between these. Git has a few concepts where the terms overlap, and the context-dependence makes it hard to give a canonical answer.

Coming full-circle to your original question: I still think the wording we've got is slightly better, in a colloquial sense, even though it's a bit ambiguous in a technical sense.

**Comment by JohnCreator** [comment]
@YueLinHo thanks. That's a helpful visualization to throw on the table.

@ben thanks again! All that makes sense and seems consistent with "My current understanding". Thanks for confirming that I've largely got it right.

>  It just seems like the shorthand for some of the concepts has you confused.

Yes, I think that's right.

> But colloquially, when we're speaking English to each other, these things are sometimes conflated. ...  Git has a few concepts where the terms overlap, and the context-dependence makes it hard to give a canonical answer.

I think that's also right and, as you suggest, generalisable to writing most technical books. 

Moreover, it's not necessarily the case that we'd want to constrain the context-dependent switch in meaning for a particular term. E.g. It's probably right to allow a "remote" to be understood, in one context, to mean the (generally) physically distant repository living on a  (generally) distant server (a more colloquial notion); and in another (closely related) context, to mean the mapping between friendly name and url that is stored in one's local repository (a more technical notion; or a notion to do with the-local-repo's-point-of-view).

> Coming full-circle to your original question: I still think the wording we've got is slightly better,

Based on my (corrected and verified) current understanding I now agree. At least the change I suggested to the single sentence would be more confusing. Especially given my discovery that `ls-remote` goes out to interrogate the remote repo, where it lives on a distant server. That command really is returning "references (pointers) in your remote repositories".

The inherent complexity of Git, as for any version control system, is invariably going to require repeated readings of the manual (here ProGit). So my initial confusion could be an idiosyncratic confusion, a confusion particular to me, that just gets corrected on further study. 

However, I suspect not. That is, that the kinds of confusion that I had after reading the first few paragraphs of Ch. 3, Git Branching, sec Remote Branches, will be something a significant number of other readers will be prone to. And that parts of the book could be improved to head off that confusion.

I don't, at this point, have the specific suggestions that it is incumbent on me to make. I suspect it would entail a rewording of the first few paragraphs of Ch. 3, Git Branching, sec Remote Branches; and parts of Ch 2. Git Basics, sec Working with Remotes.

In lieu of those specific suggestions it may be worth trying to record the specific confusions I had after my first reading of the first four paragraphs of Ch. 3, Git Branching, sec Remote Branches. Especially since those confusions have (it seems) been corrected. I think the confusions were:

* Wrongly thinking that a "remote" was a kind of "reference" and even a kind of "remote reference". Well, there remains a sense in which this is not wrong thinking ... but it wasn't what you guys were driving at. Internally, at least, and from the local-repo-point-of-view: a "remote" is quite the different beast than a "reference".

* Conflating SHA-1 references with symbolic references.

* Failing to understand that a "remote reference" is both: something stored in the remote repo; and stored in the local repo.

  The correct view is, rather, exemplified by ...

  E.g. Looking at "remote references" in a remote repo ...

      PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> git ls-remote origin
      5858a029229cccd5197106e0c723faaf5cd01eed        HEAD
      1fcefde5128f3eab7da00067ce4223cacf55eaf7        refs/heads/issue315-fruit-handling
      5858a029229cccd5197106e0c723faaf5cd01eed        refs/heads/master

  E.g. Look at "references" in the local repo, among which the "refs/remotes/*" are "remote references" (and also "remote tracking branches"). ...

      PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> git show-ref
      1fcefde5128f3eab7da00067ce4223cacf55eaf7 refs/heads/issue315-fruit-handling
      5858a029229cccd5197106e0c723faaf5cd01eed refs/heads/master
      5858a029229cccd5197106e0c723faaf5cd01eed refs/remotes/origin/HEAD
      1fcefde5128f3eab7da00067ce4223cacf55eaf7 refs/remotes/origin/issue315-fruit-handling
      5858a029229cccd5197106e0c723faaf5cd01eed refs/remotes/origin/master
      1fcefde5128f3eab7da00067ce4223cacf55eaf7 refs/remotes/upstream/master
      eb5a668372e1bb1ae859b8337ff77c281a2ed73c refs/tags/v0.1.0 

  And because, in this example, my local repo is up to date with my origin remote repo we find that the local-remote-reference `refs/remotes/origin/master` and the remote-remote-reference of the origin repo `refs/heads/master` both point to the same commit: `5858a02`.

* Failing to understand that a "remote tracking branch" is stored in the local repo. That is, despite your clear sentences, in the book, "Remote-tracking branches are references to the state of remote branches.
They’re local references that you can’t move; ...".

At this point I've finished your (and Scott's) book. I have skimmed sections in the later chapters for various reasons: they pertain to environments I'm unlikely to use; rare use cases, etc. But I'm grateful for even for those parts, for they round out the book as a somewhat complete reference (noting there's also "Git - Reference" at https://git-scm.com/docs).

And overall, to repeat, it's a superb book. Indeed I think the fore-fronting of a colloquial narrative style, liberally interspersed with images of commit trees and command line examples, while holding off on the internals - was the right approach. As you mentioned it's a tricky business to balance all these things, and you guys have largely got it right. The language flows easily and simply, despite the complexity of the subject: the mark of good technical writing.
  
So, on the current issue of whether the book could use some rewriting to head off any confusion around remotes, references, and remote tracking branches: perhaps you could let that sit with me until, or if, I come up with some specific suggestions. Perhaps, for example, we could leave this thread open and if I don't return with a suggestion in, say, a month: then you'd be warranted to close it (if I don't).

**Comment by JohnLukeBentley** [comment]
@YueLinHo thanks. That's a helpful visualization to throw on the table.

@ben thanks again! All that makes sense and seems consistent with "My current understanding". Thanks for confirming that I've largely got it right.

> It just seems like the shorthand for some of the concepts has you confused.

Yes, I think that's right.

> But colloquially, when we're speaking English to each other, these things are sometimes conflated. ... Git has a few concepts where the terms overlap, and the context-dependence makes it hard to give a canonical answer.

I think that's also right and, as you suggest, generalisable to writing most technical books.

Moreover, it's not necessarily the case that we'd want to constrain the context-dependent switch in meaning for a particular term. E.g. It's probably right to allow a "remote" to be understood, in one context, to mean the (generally) physically distant repository living on a (generally) distant server (a more colloquial notion); and in another (closely related) context, to mean the mapping between friendly name and url that is stored in one's local repository (a more technical notion; or a notion to do with the-local-repo's-point-of-view).

> Coming full-circle to your original question: I still think the wording we've got is slightly better ...

Based on my (corrected and verified) current understanding I now agree. At least the change I suggested to the single sentence would be more confusing. Especially given my discovery that ls-remote goes out to interrogate the remote repo, where it lives on a distant server. That command really is returning "references (pointers) in your remote repositories".

The inherent complexity of Git, as for any version control system, is invariably going to require repeated readings of the manual (here ProGit). So my initial confusion could be an idiosyncratic confusion, a confusion particular to me, that just gets corrected on further study.

However, I suspect not. That is, that the kinds of confusion that I had after reading the first few paragraphs of Ch. 3, Git Branching, sec Remote Branches, will be something a significant number of other readers will be prone to. And that parts of the book could be improved to head off that confusion.

I don't, at this point, have the specific suggestions that it is incumbent on me to make. I suspect it would entail a rewording of the first few paragraphs of Ch. 3, Git Branching, sec Remote Branches; and parts of Ch 2. Git Basics, sec Working with Remotes.

In lieu of those specific suggestions it may be worth trying to record the specific confusions I had after my first reading of the first four paragraphs of Ch. 3, Git Branching, sec Remote Branches. Especially since those confusions have (it seems) been corrected. I think the confusions were:

* Wrongly thinking that a "remote" was a kind of "reference" and even a kind of "remote reference". Well, there remains a sense in which this is not wrong thinking ... but it wasn't what you guys were driving at. Internally, at least, and from the local-repo-point-of-view: a "remote" is quite the different beast than a "reference".

*	Conflating SHA-1 references with symbolic references.

*	Failing to understand that a "remote reference" is both: something stored in the remote repo; and stored in the local repo.

    The correct view is, rather, exemplified by ...

    E.g. Looking at "remote references" in a remote repo ...

        PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> git ls-remote origin
        5858a029229cccd5197106e0c723faaf5cd01eed        HEAD
        1fcefde5128f3eab7da00067ce4223cacf55eaf7        refs/heads/issue315-fruit-handling
        5858a029229cccd5197106e0c723faaf5cd01eed        refs/heads/master

    E.g. Look at "references" in the local repo, among which the "refs/remotes/*" are "remote references" (and also "remote tracking branches"). ...

        PS C:\Users\John\Documents\Sda\Code\Git\Examples\example> git show-ref
        1fcefde5128f3eab7da00067ce4223cacf55eaf7 refs/heads/issue315-fruit-handling
        5858a029229cccd5197106e0c723faaf5cd01eed refs/heads/master
        5858a029229cccd5197106e0c723faaf5cd01eed refs/remotes/origin/HEAD
        1fcefde5128f3eab7da00067ce4223cacf55eaf7 refs/remotes/origin/issue315-fruit-handling
        5858a029229cccd5197106e0c723faaf5cd01eed refs/remotes/origin/master
        1fcefde5128f3eab7da00067ce4223cacf55eaf7 refs/remotes/upstream/master
        eb5a668372e1bb1ae859b8337ff77c281a2ed73c refs/tags/v0.1.0 

    And because, in this example, my local repo is up to date with my origin remote repo we find that the local-remote-reference refs/remotes/origin/master and the remote-remote-reference of the origin repo refs/heads/master both point to the same commit: 5858a02.

*	Failing to understand that a "remote tracking branch" is stored in the local repo. That is, despite your clear sentences, in the book, "Remote-tracking branches are references to the state of remote branches. They’re local references that you can’t move; ...".

At this point I've finished your (and Scott's) book. I have skimmed sections in the later chapters for various reasons: they pertain to environments I'm unlikely to use; rare use cases, etc. But I'm grateful for even for those parts, for they round out the book as a somewhat complete reference (noting there's also "Git - Reference" at https://git-scm.com/docs).

And overall, to repeat, it's a superb book. Indeed I think the fore-fronting of a colloquial narrative style, liberally interspersed with images of commit trees and command line examples, while holding off on the internals - was the right approach. As you mentioned it's a tricky business to balance all these things, and you guys have largely got it right. The language flows easily and simply, despite the complexity of the subject: the mark of good technical writing.

So, on the current issue of whether the book could use some rewriting to head off any confusion around remotes, references, and remote tracking branches: perhaps you could let that sit with me until, or if, I come up with some specific suggestions. Perhaps, for example, we could leave this thread open and if I don't return with a suggestion in, say, a month: then you'd be warranted to close it (if I don't).

(Edit: Initially posted under wrong account. That post was deleted.)

**Comment by JohnLukeBentley** [comment]
I'll close this issue. Although I still feel might be a way to better introduce and distinguish remotes, remote references, and remote tracking branches - the current text is certainly not *bad* in this respect. I'll leave it up to you @ben as an issue you might like to keep in the back of your mind if you embark an a wholistic rewrite.
