### ISSUE TITLE
Create a new repository for pt-BR

### ISSUE THREAD

**Issue by filhocf** [progit/progit2#742]
Please, open a new repo for brazilian portuguese.

**Comment by jnavila** [comment]
There's already one, that is published on git-scm.com:

https://github.com/progit2-pt-br/progit2

**Comment by filhocf** [comment]
Thank you by your fast reply @jnavila . I will take a look and will help there, so. 

IMHO, could be better to have a repo under progit2 user. Anyway, they have only the first chapter translated.

**Comment by jnavila** [comment]
That's no longer useful to have all the languages under progit2 organization, because as users, you would have less rights on the repo (mine are very restricted for progit2/progit-fr). The build workflow through Atlas is no longer active, which was the main incentive to gather all the translations under one organization.

**Comment by rogeriopradoj** [comment]
@filhocf hello, please join us in pt-br efforts there, you and everyone interested on it are more than welcome! https://github.com/progit2-pt-br/progit2 and @rogeriopradoj!
