### ISSUE TITLE
images folder missing when creating pdf file

### ISSUE THREAD

**Issue by bremenpl** [progit/progit2#764]
Hello there,
I have cloned the repo and tried to generate a pdf version of the book by using:
`asciidoctor-pdf progit.asc`
I received a lot of error messages informing that all of the *.png images could not be found in directory images:
`image to embed not found or not readable`
It was because directory images does not exist. I had to create one and copy all `*.png` files I could find in the repo:
`lukasz@debkde:~/progit2$ pwd | find -name "*.png" -type f -exec cp {} ./images \;`
After that I could run `asciidoctor-pdf progit.asc` to generate the book. I really appreciate it, thanks.

**Comment by aollier** [comment]
You're right.
The repository images does not exist because it is ignored:
```
$ cat .gitignore
output
.DS_Store

# build artifacts
Gemfile.lock
progit.html
progit.pdf
progit.pdfmarks
progit.epub
progit-kf8.epub
progit.mobi
/images/
```

Building the book properly is made by calling `bundle exec rake` which calls `Rakefile` which create the folder and copies the images contained in book/ into the `images` folder:

```Ruby
  desc 'prepare build'
  task :prebuild do
    Dir.mkdir 'images' unless Dir.exists? 'images'
    Dir.glob("book/*/images/*").each do |image|
      FileUtils.copy(image, "images/" + File.basename(image))
    end
  end
```

So the good command to get only the required images into the images folder is:
```Bash
# create and fill the images folder (do it only once)
mkdir images
find book/ -name '*.png' -and -type f -exec cp '{}' images/ \;
# generate the PDF
asciidoctor-pdf progit.asc
```

I'll update README.md with those instructions.
