### ISSUE TITLE
"asciidoc" package mostly renamed to "asciidoctor" or "rubygem-asciidoctor"

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#856]
"Installing from Source" section probably needs updating, as it refers to the "asciidoc" package, which seems to have been renamed, based on your distro. On my Fedora 26 system, it's called "rubygem-asciidoctor"; on Ubuntu, it appears to be called "asciidoctor"; and EPEL seems to call it "rubygem-asciidoctor" as well. I'll clarify all this and submit a patch in my copious free time.

**Comment by ben** [comment]
Where are you finding this? The [readme](https://github.com/progit/progit2/blob/master/README.asc) only mentions asciidoctor.

**Comment by rpjday** [comment]
Chapter 1, "Installing from Source", the second set of example installation commands:

$ sudo dnf install asciidoc xmlto docbook2X getopt 
$ sudo apt-get install asciidoc xmlto docbook2x getopt

**Comment by ben** [comment]
Ah, this is in the book. In that case, that's a specific dependency that Git has for building its documentation. I _seriously_ doubt they use Asciidoctor, since that would imply that you'd need Ruby installed. Asciidoc is not the same as Asciidoctor, and [has installation instructions](http://www.methods.co.nz/asciidoc/INSTALL.html).

**Comment by rpjday** [comment]
Ah, understood. I'll close this issue.

**Comment by jnavila** [comment]
The last time I checked, Git was using asciidoc, but still provided an option to use asciidoctor. There's some work to adapt the git manpages to be compatible with asciidoctor, mainly because of git-scm.com.
