### ISSUE TITLE
Where are Finnish translations?

### ISSUE THREAD

**Issue by t-my** [progit/progit2#857]
- I'd like to contribute to the Finnish translations, where are they? 
- In [CONTRIBUTING.md](https://github.com/progit/progit2/blob/master/CONTRIBUTING.md) it is said that there are different repositories under [ProGit](https://github.com/progit) organization. I can't find progit2-fin. Where is it? 
- However, I can see that there are some translations already, look: [https://git-scm.com/book/fi/v1](https://git-scm.com/book/fi/v1).

**Comment by jnavila** [comment]
Thanks for hitting the point!

The Finnish translation available on git-scm.com is still the first edition. You can find the sources in [progit/progit](https://github.com/progit/progit/).

This version is now outdated and patches on it are strongly discouraged (for once, the changes are no longer pushed to git-scm.com).

That version should be updated to be in sync with the second edition in English, available here. To do so,
 
 1. create a github organization, say `progit2-fi' on github
 2. create a project progit2
 3. copy the structure of progit/progit2 in your project and start translating. You can reuse some material from the first edition, but beware that:
   3.1. the text has been reworked in numerous parts
   3.2. the markup has changed from markdown to asciidoc
 4. Push to the new repo a few translated chapters
 5. ping me so that I add processing on git-scm.com for the second edtion of Finnish progit2.

**Comment by HonkingGoose** [comment]
@jnavila Your thoughts on this issue?

**Comment by jnavila** [comment]
This thread was used as a draft for the content of the TRANSLATING file. Let's close it now

**Comment by jnavila** [comment]
The Finnish translation never took up. The first edition of the book has been retired. So let's close this issue.
