### ISSUE TITLE
ePub Validation Issues

### ISSUE THREAD

**Issue by jxramos** [progit/progit2#925]
Uploading the epub file to http://validator.idpf.org yields multiple validation issues with the ebook.
I've attached a printout of the web page's results for review.

[ValidationResults.pdf](https://github.com/progit/progit2/files/1451970/ValidationResults.pdf)

**Comment by jtcmedia** [comment]
This may be related to the fact that the ePub can't be processed by Google Books.

**Comment by jxramos** [comment]
Hmm, looks like there was an earlier issue #111 that was resolved and closed; did the document regress or maybe some code gen type processes are still broken?

I recently downloaded https://github.com/progit/progit2/releases/download/2.1.14/progit.epub to trigger these errors with.

**Comment by jnavila** [comment]
The structure of the book does not fit with the ebook-generation toolchain (asciidoc). To get rid of these errors, the file structure of the book should be reworked, which is a big work.

**Comment by jxramos** [comment]
So the flaw is in the content of the eBook and not a shortcoming of asciidoc's? I'm trying to get a clear sense of where the effort would need to go, not patching ascidoc's backend engine but reorganizing something in the git documents themselves.

Would you mind sharing a sketch of the procedure involved in resolving  how one of the validation errors would get eliminated. Is the repair work mainly a large volume of repetitive fixes or something more nuanced and interconnected like a bulk of dependencies fixed simultaneously or something with complex chained feedbacks, I don't know. Thank you.

**Comment by jnavila** [comment]
We're using asciidoctor and most of the limitations come from it. The structure of the files as of now are inherited from the setup for the previous edition toolchain (O'Reilly's Atlas). Now [asciidoctor-epub3](https://github.com/asciidoctor/asciidoctor-epub3) is used and you can see in the README file, the structure to make it work is very precise.

I did it for [progit2-fr](https://github.com/progit/progit2-fr/tree/reorder_files) and it involved changing everything according to the requirements. I also found some bugs in asciidoctor-epub3 that are fixed in the master branch but not yet released in a version.

Changing the way asciidoctor-epub3 behaves is a big task, and the simplest is to change the structure of the book, if @ben agrees.

**Comment by ben** [comment]
I'd accept that PR. It might create conflicts for all the other open PRs, and make it harder for translations to backtrace to the original English, but it seems like the right move going forward.

**Comment by yunhailuo** [comment]
Not sure if anyone is working on this. I did a partial fix and sent a [PR](https://github.com/progit/progit2/pull/932). You will need to use asciidoctor-epubs "1.5.0.alpha.8.dev" to make the epub since the release alpha 7 has a bug in generating image ID. As I tested, the epub generated from "1.5.0.alpha.8.dev" should be able to pass EPUB Validator and should be able to be loaded onto Google Books. @jtcmedia @jxramos @ben
