### ISSUE TITLE
Adding new language

### ISSUE THREAD

**Issue by fekir** [progit/progit2#930]
Hello,

I'm going to read the book in English and noticed that there is no German translation.

I thought I could try to translate the book while reading it, but it's unclear to me how to contribute.

https://github.com/progit/progit2/blob/master/CONTRIBUTING.md states that I need to "create a GitHub organization" on github.

Wouldn't a simple feature branch or project be enough?

I'm reading right now how to create an organization (https://help.github.com/articles/creating-a-new-organization-from-scratch/), but I can't see why this is needed.

And regarding step 3: "Copy the structure of progit/progit2 (this project) in your project and start translating."

I suppose it would be therefore OK if at the beginning most text is still in English and not German, or does the project need to be mostly translated in German before it is accepted?

And since translations are on separate repositories, how does it work when/if the English version is updated with new content?

Best regards
Federico

**Comment by ben** [comment]
Yeah, those instructions are kind of out-of-date, we should fix that.

Rather than fork the original repo, which creates linkages, go ahead and create `progit2-de` under your account, add it as a remote to your `progit2` clone, then do `git push <new-remote> master`. Once that's done, we'll transfer your repo into the progit2 org and get you into the list of translations.

> I suppose it would be therefore OK if at the beginning most text is still in English and not German, or does the project need to be mostly translated in German before it is accepted?

Yeah, this is how most translation projects proceed. It would be unrealistic to expect 100% translation before we get a project listed on the git-scm.com page.

> And since translations are on separate repositories, how does it work when/if the English version is updated with new content?

We don't have a really good workflow for this, and Git doesn't help very much. Most of the changes coming through right now are grammar and spelling corrections, with the occasional technical update. You could hit "watch" on this repo and start getting emails whenever new PRs come in. The volume isn't very high, and then you'd know if something major is changing.

**Comment by jnavila** [comment]
> I'm reading right now how to create an organization (https://help.github.com/articles/creating-a-new-organization-from-scratch/), but I can't see why this is needed.

This is a simpler way to share the project rights across several translators and to allow the translation project to live on its own. Then you can distribute the administrative rights to other translators, because you own the organization. This relaxes the burden on managing the translation repo for the owners of the progit org.

> And since translations are on separate repositories, how does it work when/if the English version is updated with new content?

Good point, I'm still fighting to get something workable on that :fist_left: The main idea was to use [po4a](https://github.com/mquinson/po4a) to get a translation memory of each sentence of the book. But this does not work great… If you have any solutions, that'd be quite appreciated!

**Comment by fekir** [comment]
What about writing a tag in the commit message when changing the semantic of the content?

This way it should be possible to filter all commits that may be relevant for other translations...

**Comment by jnavila** [comment]
That would put a burden on contributors, making it hard to propose changes.

**Comment by fekir** [comment]
It could be also done the other way round.

Maybe its possible to provide a script that will rebase the feature branch, check if the commit message begins with a specific pattern, if not reword it by adding the tag. (for example: "[translation]")

Of course such approach would work only on feature branches where contributors are only changing content, and not translating too.

**Comment by jnavila** [comment]
I am not sure I'm following you. What's the purpose of this proposition? To set up a workflow for tagging commits that contain contents which impact the translations. Translations occur in other repositories, so there's not translations in this one. 

Now judging that a change will have or not an impact for translations is a matter of understanding whether the change is semantic. I don't think that this type of tagging can be mechanized.

**Comment by fekir** [comment]
I picked a horrible tag.

Something better would be "fix", "new-content", ...

This way, the other repositories, can grep for "new-content" (or exclude "fix") in the history, and the output should be (more or less) the missing new content from their repositories.

I do not think either that this tagging can be completely mechanized, such a script would be useful for those merge request where someone is fixing typos, add clarifications and so on, but not adding or deleting content.
Such a PR, wouldn't be that interesting for someone that is maintaining the translation of the book. 

I said that a script could be useful for lowering the burden, since I imagined that you did not want to tell people to reword every commit they made in the feature branch if the content is not meaningful for the translation repositories.

**Comment by parkinson101** [comment]
#1016

**Comment by HonkingGoose** [comment]
@jnavila This issue was opened to start a German translation which is now visible both in the [git-scm webpage](https://git-scm.com/book/de/v2) and on the TRANSLATING.md table of translations.

What are your thoughts on this issue?

**Comment by jnavila** [comment]
The proposition was partly followed. I guess we can close it now.
