### ISSUE TITLE
10.5 Git Internals - The Refspec, pulling a branch on the remote down to local one with different name

### ISSUE THREAD

**Issue by ksiazekm** [progit/progit2#946]
In the '10.5 Git Internals - The Refspec' can be found:

> If you want to do a one-time only fetch, you can specify the specific refspec on the command line, too. To pull the master branch on the remote down to origin/mymaster locally, you can run:
> 
> `$ git fetch origin master:refs/remotes/origin/mymaster`

But when I tried it just empty local branch has been created which is shown as stale one by show command. Details are described here: [git fetch to different local remote refspec](https://stackoverflow.com/questions/47983314/git-fetch-to-different-local-remote-refspec)

**Comment by ben** [comment]
What this _should_ do is create a local remote-tracking branch called `origin/mymaster`, which points to the commit that `master` points to on the `origin` remote. Since it's a remote-tracking branch, it shouldn't show up in `git branch`, and shouldn't be reported as stale. Can you post your output?

**Comment by ksiazekm** [comment]
The all output is in the link I'd provided in the issue, it is:  [https://stackoverflow.com/questions/47983314/git-fetch-to-different-local-remote-refspec](https://stackoverflow.com/questions/47983314/git-fetch-to-different-local-remote-refspec)

**Comment by ben** [comment]
Oh, this part:

```
bash$ git remote show origin
  Remote branches:
master                      tracked
refs/remotes/origin/master2 stale (use 'git remote prune' to remove)
```

That makes sense. If I had done a normal fetch, and got the remote's `master` and `foobar` branches, but then the `foobar` branch got deleted on the remote, I'd expect my `origin/foobar` branch to be "stale." That's what Git is saying: it asked the remote, and there is no `master2` branch there. Does that make sense?

Maybe we should change this command to fetch to a regular branch, instead of faking a remote-tracking branch. Want to submit a PR?

**Comment by KZiemian** [comment]
Can this issue be closed?
