### ISSUE TITLE
Getting Started - Git Basics ambiguous explanation

### ISSUE THREAD

**Issue by stepaniuk** [progit/progit2#951]
The basic Git workflow goes something like this:
1. You modify **files** in your working tree.
2. You selectively stage just those __changes (?)__ you want to be part of your next commit, which adds only those __changes (?)__ to the staging area.
3. You do a commit, which takes the **files** as they are in the staging area and stores that snapshot
permanently to your Git directory.

**Comment by ben** [comment]
This is ambiguous because you can think of the index as either :a: a place to stick changes until you're ready to make a commit with just the changes you want, or :b: a holding area for the tree that the next commit will point to. Of these, :b: is more technically correct, but both models are useful in different contexts. Does that make sense? 

The index is one of the big points of confusion to people new to Git. Can you point to a place in the text where we could do this better?

**Comment by stepaniuk** [comment]
> both models are useful in different contexts

Yes, but I think that within that context it is better to stick to just one model

**Comment by ivbaoxing** [comment]
Work With Us
We’re the guys behind SE Asia’s leading mobile-financial comparison websites: Malaysia's RinggitPlus.com and Indonesia's KreditGoGo.

We also provide awesome Managed Services and a Conversational Marketing Platform to companies across APAC. Our clients are some of the biggest names in Banking and Insurance, and beyond.

On the Backend we're doing some really interesting things with all of your favourite cloud services, mostly using Golang and Docker, and we're creating some neat chatbots this year.

On the Front End we're mobile-first all the way. This doesn't mean we pay lip-service to responsiveness with a touch of HTML5, it means we strive to make our web applications feel native, and we know what it takes to deliver a good user experience over a mobile network.

We're a tight-knit team of twenty developers and product people. We all absolutely love what we do and consider work like playing with a very big and powerful toy box.

If you don't ever want to stop learning and like to stay ahead of the pack, join us. You'll have fun, get paid for it.

**Comment by stepaniuk** [comment]
Ok, sorry, I am going to close the issue.
