### ISSUE TITLE
3.0 Git Branching - Remote Branches - Tracking Branches: "Merge in" instead of "merge into"

### ISSUE THREAD

**Issue by uerdogan** [progit/progit2#963]
> If you’re on a tracking branch and type git pull, Git automatically knows which server to fetch from and branch to **merge into**.

I've understood this as a compact version of this english sentence (Am I right?):

> If you’re on a tracking branch and type git pull, Git automatically knows which server to fetch from and _**which**_ branch to **merge into**.

So I think the **_original sentence_** should be changed to:

> If you’re on a tracking branch and type git pull, Git automatically knows which server to fetch from and branch to **merge in**.

because mentioning that _... `you're on a tracking branch` ..._ would make the following _`Git automatically knows ... which branch to merge into`_ not sound very smart. It is obviously that the current branch, which you are staying in, is the one to **merge into**.
But what would be smart by git is, that it derives the information which remote branch it will **merge in**.

See also figure 3-16: Three snapshots used in a typical merge.

I hope you understand what I am trying to say in my poor english.

**Comment by ben** [comment]
Sort of. What's really happening when you do a `git pull` is:

1. `git fetch`
2. `git merge`

The first operation is unambiguous. Fetch always does the same thing. The second one is a bit trickier. Git can create a merge between any two commits, so which ones does it choose?

On a human level, this is easy. I'm on `master`. See that branch `master` in the remote you just fetched from? Yeah, that's the one I want to merge into my `master`. But Git doesn't assume you want that, especially since you can have many remotes, any or all of which might have a `master` branch in them.

So there's a config section that resolves the ambiguity so Git knows that when I'm on `master` and I type `git pull`, I want it to be associated with the `master` from the `origin` remote, and not any other remotes or remote branches. So now Git can proceed with

1. `git fetch origin`
1. `git merge origin/master`

So there's the background. How to describe this? Well, when the merge happens, it's taking the changes from `origin/master` and merging them into my local `master`. So you can understand how the sentence came to end with "Git automatically knows which server to fetch from and branch to merge into."

But you're right, this could be clearer. Want to submit a PR with a better version? I like adding in the "which" at the very least.

**Comment by uerdogan** [comment]
I see your point.

What I had understood **from the labels of figure 3-16** led me to the following point of view:
The origin/master branch is the one, in the merging process, which is **merged in** and
the local/master branch is the one, in the same process, into which is being **merged into**.

So I would like to suggest two alternative formulations:
1) Git automatically knows which server to fetch from and **which** branch to merge **in**.
2) Git automatically knows which server to fetch from and **which** branch to **use for merging** into.

As you see, nr 1 is the same from my original post because of above explanation about figure 3-16 and therefore not ambigious for me.

Please let me know your opinion.

**Comment by ben** [comment]
Yeah, 1 seems like a good way to resolve this.
