### ISSUE TITLE
Submodules section is either misleading or wrong in the case of nested submodules

### ISSUE THREAD

**Issue by BenSandeen** [progit/progit2#964]
In the "Working on a Submodule" section, after telling me to go into a submodule and checking out a branch, it seems to be saying that running the command `$ git submodule update --remote --merge` will find any updates on the submodule's remote repo and merge them into the submodule.

However, I have set up a parent repo named `parent`, which has a submodule named `submod`, which in turn has its own submodule named `subsubmod` to see what happens when I ran the above command in the `submod` repo when both `submod` and `subsubmod` had newer commits on their respective remote repos.

As I expected, running `$ git submodule update --remote --merge` within the `submod` submodule of the `parent` repo (but without the `subsubmod` submodule of the `submod` submodule) updated only the `subsubmod` submodule and not the `submod` module (excluding the update to its submodule `subsubmod`, of course).

I don't know enough about git to proffer a potential rewrite of this section, but unless I'm doing something incorrectly, this section is misleading at best.

**Comment by phil-blain** [comment]
The `git submodule update` command is used to update the submodules _of the current repo_, so the behaviour you describe is normal. A git repo doesn't "know" if it is used a submodule.

In short:
**When in `parent`:**
`git submodule update --remote --merge` will fetch the remote for `submod` and merge any new commits
`git submodule update --remote --merge --recursive` will fetch the remote for `submod` and merge any new commits, and also fetch the remote for `subsubmod` and merge any new commits.

**When in `submod`:**
`git submodule update --remote --merge` will fetch the remote for `subsubmod` and merge any new commits
`git submodule update --remote --merge --recursive` will do the same, since `subsubmod` doen't have any submodules.

**When in `subsubmod`:**
`git submodule update --remote --merge`, with or without `--recursive`, will do nothing since `subsubmod` doesn't have any submodules.

I think your confusion comes from the following section of the chapter  :

> First of all, let’s go into our submodule directory and check out a branch.
> 
> ```
> $ git checkout stable
> Switched to branch 'stable'
> ```
> Let’s try it with the “merge” option. To specify it manually, we can just add the --merge option to our update call. Here we’ll see that there was a change on the server for this submodule and it gets merged in.
> 
> ```
> $ git submodule update --remote --merge
> ...
> ```

Between the two commands `git checkout stable` and `git submodule update --remote --merge`, there is an implicit `cd ..` step to go back to the MainProject repo ! You are right that this could be clearer. @ben what do you think? I could do a small PR for that.

**Comment by ben** [comment]
Sure, I'd love to see a PR.
