### ISSUE TITLE
Localization/Translation to Filipino

### ISSUE THREAD

**Issue by Cyyy1998** [progit/progit2#983]
Good day,

 Can I translate this project to my native language which is Filipino ?

**Comment by jnavila** [comment]
Please read the [CONTRIBUTING document](https://github.com/progit/progit2/blob/master/CONTRIBUTING.md) . This repository does not accept PR for translations.

**Comment by Cyyy1998** [comment]
What does PR means ?

**Comment by jnavila** [comment]
PR = pull request, meaning proposed changes. The translations don't change this repository, they take place in their own project.

**Comment by lazarljubenovic** [comment]
Just curious. Was the book featured somewhere? Was there a call for translators? Suddenly there's _a lot_ of people wanting to contribute!

**Comment by jnavila** [comment]
They're all coming from [utopian.io](https://utopian.io) I still don't quite understand how it works, but it seems there's some way of making money out of it.

**Comment by Cyyy1998** [comment]
Okay thanks for your time

**Comment by jnavila** [comment]
@lazarljubenovic I know a bit of european languages and have the ability to have some asian languages reviewed. But here, we're talking about some asian languages which have not passed much through the borders of their origin countries, and for which, although the number of native speakers (Cebuano is 21 millions according to Wikipedia and Tagalog, an official language in Philippines), we must rely on the good faith of the translators and their peer reviews (which utopian.io rewards also, it seems).

We have no reason to push them aside, and by just accepting the new translations while waiting for the wave to end, paradoxically, we provide translations of this book that will help more people come into the community, pushing up the number of contributions, which in the end may not end the wave 😉 .

Now for the dubious translations, it's up to the translators to organize themselves, and if it happens that a translation is reported to be of bad quality, we can always remove it from the list here and from git-scm.com.

@Cyyy1998 Filipino and Tagalog are the same language, aren't they? In this case, please head for the tagalog translation project.

**Comment by plokmi** [comment]
@jnavila well, I can provide some information on this. Utopian.io is built on STEEM blockchain, which is a decentralized platform which pays quality contents in terms of STEEM token. Basically, how it works is, according to the [Utopian.io rules](https://utopian.io/rules), if you contribute to an Open Source Project which fulfill the criteria and abide by the rules, you can get rewarded by the platform Utopian.io itself. 

The thing is, apparently, translation will be the easiest category to be rewarded since, basically if you know English and your native language, you can contribute on the platform. Speaking as a moderator on the platform myself, there are a lot of abuse in the past, where contributors took advantages of the managers not knowing the particular language, and thus used Machine Translation (i.e. Google Translate) to smuggle in their translation works.

**Comment by jnavila** [comment]
@Cyyy1998 there's already a project [here](https://github.com/progit2-tl/progit2) that would surely be willing to accept new translators to work with.

@plokmi Thanks for the tips. As I said, we can neither check the quality of all translations. You write "in the past", is it over now?

**Comment by Cyyy1998** [comment]
For clarification it means you accept my request ?

**Comment by plokmi** [comment]
What I can suggest is you can search their name up on the platform itself (i.e. plokmi, then you can try to find utopian.io/plokmi for instance, albeit they can impersonate the identity sometimes), or ask them to provide some proofs of accepted translations before, so that they can't actually abuse the platform and at the same time providing bad translations for your work.

In the past, we used Crowdin.com, but they do not have automated API to help us the moderators to proofcheck the quality of translations. We've decided to drop CrowdIn support for the moment, hence this explains a sudden inflow of translations requests for projects on Github. And actually, to be frankly honest, moderators should be checking whether contributions abide by the rules or not, and not actually proofreading the work. (Utopian.io is not the second Crowdin anyway!)

**Comment by plokmi** [comment]
@jnavila Now, most of the translations accepted are on the project which have active project managers, so bad translations dropped down a bit. I agree with what you've said, but I will suggest you to appoint someone as project manager for translations specifically, or like you said, give the community some times to spot the bad translations.

That's being said, it's just my 2 cents. Am actually just would like to give you a head up regarding the possible scenario, (which can be bad).

**Comment by jnavila** [comment]
@Cyyy1998 It's not up to me to accept your request. As I said, it's up to the translators already working in your language. Go to there project and ask them.

@plokmi OK, things can go bad. Until now, we weren't considering ourselves as community managers,  things were just getting along by people volunteering to help. That's a change in the work to be carried on, we'll have to think about it.

**Comment by Cyyy1998** [comment]
Ok thanks

**Comment by plokmi** [comment]
@jnavila That's being said, we can't disregard those who will be contributing quality translations work for your project too. Anyway, sorry for hijacking the thread!

**Comment by jnavila** [comment]
@plokmi we're ready to take the chance, I think. But that brings up the question of easily setting up and managing a community with semi-autonomous sub-communities.

**Comment by plokmi** [comment]
@jnavila Well I honestly got no idea what do you mean by that, but sounds interesting haha! Will definitely to see how it works thou. Anyway, we can trust the community to do some works too. For instances, the tagalog community is being managed by one trustworthy translator ([profile here](https://utopian.io/@shoganaii)), who has over 50 accepted translations at the moment.
