### ISSUE TITLE
"git submodule update --init --recursive"??

### ISSUE THREAD

**Issue by rpjday** [progit/progit2#992]
Section "Cloning a Project with Submodules" reads, "The DbConnector directory is there, but empty. You must run two commands: git submodule init to initialize your local configuration file, and git submodule update to fetch all the data from that project ..."

Rather than running those two separate commands, is that not equivalent to:

`  $ git submodule update --init --recursive`

??

**Comment by ben** [comment]
Yes, but the point of that section is to explain the steps involved in getting the submodules set up. Just like we explain `pull` in terms of `fetch` and `merge`, we explain `clone` first, then `submodule init`.

We introduce the `--recurse-submodules` flag three paragraphs down from here. That flag is deprecated, we should probably switch to `--recursive`.

**Comment by rpjday** [comment]
"--recurse-submodules" is deprecated with respect to ... what Git commands? I never noticed anything in any of the current Git man pages that suggested that. Pointer?

**Comment by ben** [comment]
Sorry, I misread your question, and also the docs. Turns out `git clone --recursive` is deprecated, in favor of the more descriptive `--recurse-submodules`, so there's nothing there we need to update.

So you're talking about `git submodule --init --recursive`. Which yes, that's exactly what those two commands will be equivalent to. We show the basic steps, then we show how to skip them using `clone`, but we don't show how to skip them using `submodule update`. So yeah, there's an improvement we could make there.
